version: '2'
services:
  nginx:
    image: nginx:1.17
    container_name: nginx
    ports:
      - "8170:80"
    volumes:
      - "./nginx_config:/etc/nginx/conf.d/"
    depends_on: 
      - server
      - client
  server:
    build: ./docker/golang
    container_name: server
    working_dir: "/.go/src/github.com/Wisteria30/J-analyzer/"
    command: /.go/bin/air
    ports:
      - "8180:3000"
    volumes:
      - ./server:/.go/src/github.com/Wisteria30/J-analyzer/
    tty: true
  client:
    build: ./docker/nuxt
    command: yarn dev
    container_name: client
    working_dir: "/app"
    ports:
        - "8190:3000"
    volumes:
        - "./client:/app"
    tty: true
